### ISSUE TITLE
Combine it with inventory system 

### ISSUE THREAD

**Issue by Koalamana9** [expressobits/vitals#1]

**Comment by scriptsengineer** [comment]
I like to keep things separate, the idea of this addon is to have an easy way to score, hunger, health, thirst, etc. of the player, I believe it is not too linked to the inventory system.

For example, the inventory system can have items that satisfy hunger, but I leave that to the developer to implement, as there are a thousand ways this can be done.
For example some games eat means:
-> Increase your health
or
-> Increase satiety
or
-> Increase Stamina
or
-> Increase your weight

Or even another way that I can't even imagine here.
The idea of the addon is precisely to make this easier to use.
In the future, I may have example scripts with the two linked perhaps.
